name: ElIntiJA Backend CI/CD | Deploy

on:
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Copy dotenv file
        run: php -r "file_put_contents(__DIR__ . '/.env', '${{ secrets.DOT_ENV }}');"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy app
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.SSH_HOST}}
          KEY: ${{secrets.SSH_PRIVATE_KEY}}
          USER: ${{secrets.SSH_USER}}
          ARGS: -ravz --exclude=/.git/ --exclude=/.github/
          SOURCE: ./
          TARGET: /home/${{ secrets.SSH_USER }}/docker/php/www
          VERBOSE: true
          POST_SCRIPT: |
            docker exec -t php php artisan cache:clear        
            cd /home/${{ secrets.SSH_USER }}/docker/php/www
            chmod -R 777 storage
            chmod -R 777 bootstrap/cache

      - name: Verify that the service has been restarted
        run: ssh staging 'sleep 30 && curl --fail -I http://localhost:8080 || exit 1' # Si la petición falla, el paso de verificación falla
